### ISSUE TITLE
About Us - Wireframe

### ISSUE THREAD

**Issue by charliecai00** [software-assignments-spring2022/final-project-codehunt#28]

**Comment by andrewshin02** [comment]
![About-Us-Page](https://user-images.githubusercontent.com/59899452/155806397-0984dfb6-488c-4687-bb7e-256f326fbc8b.png)

**Comment by andrewshin02** [comment]
Let me know what you think! I don't know how to send over the actual draw.io/XML file. Please let me know if you would like them as well, and if there's anything to change above!
